### ISSUE TITLE
Extension missing.

### ISSUE THREAD

**Issue by camiflappy** [xgi/houdoku-extensions#10]
Good night, xgi.
Lectormanga extension doesnt seem to appear in the extensions list, despite appearing in the [@houdoku scope on the npm registry](https://www.npmjs.com/package/@houdoku/extension-lectormanga).

Would there be any way to add the extension files manually? I have tried reinstalling the app, to no success.

![image](https://user-images.githubusercontent.com/88768296/130313496-b7fa5475-8914-44ed-ad0d-477c54ea354f.png)

![image](https://user-images.githubusercontent.com/88768296/130313504-db352eeb-cc06-4bd5-b681-9a89bde929ad.png)

**Comment by xgi** [comment]
I actually noticed this yesterday -- it was a minor bug where Houdoku was only reading the first 20 entries from npm, so it wasn't getting some of the extensions. I already fixed the bug, but I'll update the client this weekend. Thanks!

**Comment by camiflappy** [comment]
Thank you! Looking forward to the update
