### ISSUE TITLE
[Source Request] kouhai.work

### ISSUE THREAD

**Issue by Razi1660** [xgi/houdoku-extensions#12]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

Kouhai Scanlations

### Source URL

https://kouhai.work/

### Source language(s)

English

**Comment by xgi** [comment]
Added. Thanks!
