### ISSUE TITLE
[Source Request] ReadComicOnline

### ISSUE THREAD

**Issue by drcorg** [xgi/houdoku-extensions#13]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

ReadComicOnline

### Source URL

https://readcomiconline.li

### Source language(s)

English

### Additional information

Western comics instead of manga, but would be very appreciated

**Comment by xgi** [comment]
Added, thanks!

**Comment by drcorg** [comment]
I should've mentioned this beforehand, but would it be possible to add a "High Quality" option to the extension settings? By default the website's reader will have it's quality set to low, and that seems to be what Houdoku is using. Thank you again

**Comment by xgi** [comment]
Oh, I hadn't realized there was a separate quality option. I've updated the extension to use high quality by default, but added an extension setting to use the low quality version. Let me know if it doesn't work for you, thanks!
