### ISSUE TITLE
Pages don't load using LectorManga extension

### ISSUE THREAD

**Issue by Kioraga** [xgi/houdoku-extensions#14]
### Acknowledgements

- [X] Ensure that your extensions are up-to-date (check the Extensions tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with Houdoku itself, open a ticket in the [Houdoku repo](https://github.com/xgi/houdoku/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.7.1

### Affected extension(s)

LectorManga 1.1.1

### Steps to reproduce

1. Adds a series from LectorManga extension.
2. Open any chapter.

### Expected behavior

It should load the chapter pages.

### Actual behavior

Currently, the only thing displayed is the name of the page and an icon indicating that the image could not be loaded.

**Comment by xgi** [comment]
Came up with a mitigation for this; please update the extension to 1.1.2.

It may be a bit slow right now -- pages will get loaded sequentially. Assuming it works, I'll see if I can improve the performance later.
