### ISSUE TITLE
[Source Request] AnzManga

### ISSUE THREAD

**Issue by Kioraga** [xgi/houdoku-extensions#15]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

AnzManga

### Source URL

https://www.anzmangashd.com/

### Source language(s)

Spanish

**Comment by xgi** [comment]
Moved to #85
