### ISSUE TITLE
[Source Request] nhentai

### ISSUE THREAD

**Issue by D33NCRYP73D** [xgi/houdoku-extensions#16]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

nhentai

### Source URL

https://nhentai.net

### Source language(s)

"English", "Japanese"

**Comment by xgi** [comment]
I'm considering adding some flags/filters in the UI on the extensions page before adding purely NSFW sources. But I'd be willing to add this source after that.

**Comment by xgi** [comment]
Added!
