### ISSUE TITLE
[Source Request] Komga

### ISSUE THREAD

**Issue by noaione** [xgi/houdoku-extensions#19]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

Komga

### Source URL

https://komga.org/

### Source language(s)

Multi

### Additional information

Source code: https://github.com/gotson/komga
Demo URL: https://demo.komga.org/
Demo account: `demo@komga.org` / `komga-demo`
Demo Swagger UI page: https://demo.komga.org/swagger-ui.html

Komga is a self-hosted media server for comics, mangas, and more.

The extension options should at least includes base server url, email, and password.
For authentication, it use simple Basic Auth which will set the `SESSION` cookies automatically on any API path.

I would not mind helping creating the extension.

**Comment by xgi** [comment]
This seems interesting, I'd like to add support for it. I'll start working on it later this week and update if I find there will be any major hurdles. Thanks!

**Comment by bayang** [comment]
Hi have you made any progress on this extension so far ? 
I'm a komga user but don't like reading in the web browser, this could be a perfect fit for my use case.
Thanks !

**Comment by xgi** [comment]
When I looked at this before, I found it would require an update to the client to support. I just made a card in the main repo with some more info to track that addition: https://github.com/xgi/houdoku/issues/179
