### ISSUE TITLE
[Source Request] Asura scans

### ISSUE THREAD

**Issue by rayandev2003** [xgi/houdoku-extensions#20]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

Asura Scans

### Source URL

https://www.asurascans.com/

### Source language(s)

"English"

**Comment by xgi** [comment]
Moved to #85
