### ISSUE TITLE
[Source Request] Golden Mangas

### ISSUE THREAD

**Issue by trueSamukinha** [xgi/houdoku-extensions#21]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

Golden Mangas

### Source URL

https://goldenmanga.top

### Source language(s)

Brazilian Portuguese

### Additional information

I got a little confused. In the settings it's possible to choose Brazilian Portuguese as the language of the chapters, so I thought there was some Brazilian extension. I will be very happy if you add this. :)

**Comment by xgi** [comment]
Moved to #85
