### ISSUE TITLE
[Source Request] Submanga

### ISSUE THREAD

**Issue by AUKUMA** [xgi/houdoku-extensions#22]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

Submanga

### Source URL

https://submanga.io/

### Source language(s)

Spanish

**Comment by AUKUMA** [comment]
please add submanga

Lectormanga, gets slow and unreadable at times, add submanga for some alternative to read in Spanish.

**Comment by xgi** [comment]
Moved to #85
