### ISSUE TITLE
[Source Request] MangaReader 

### ISSUE THREAD

**Issue by Laezor** [xgi/houdoku-extensions#23]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

MangaReader

### Source URL

https://mangareader.to/

### Source language(s)

English, Japanese

### Additional information

High-quality scans.
Anti-overload with back-up server.
Fast content updates.
Zero ads and pop-ups.

**Comment by xgi** [comment]
Moved to #85
