### ISSUE TITLE
[Source Request] Nitro Scans

### ISSUE THREAD

**Issue by dragow0lf** [xgi/houdoku-extensions#24]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

Nitro Scans

### Source URL

https://nitroscans.com

### Source language(s)

English

**Comment by xgi** [comment]
Moved to #85
