### ISSUE TITLE
Mangakik Source Bug

### ISSUE THREAD

**Issue by dragow0lf** [xgi/houdoku-extensions#25]
### Acknowledgements

- [X] Ensure that your extensions are up-to-date (check the Extensions tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with Houdoku itself, open a ticket in the [Houdoku repo](https://github.com/xgi/houdoku/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.8.0

### Affected extension(s)

Mangakik 1.2.0

### Steps to reproduce

Open any manga using the extension

### Expected behavior

It should bring up the "add series to library" popup

### Actual behavior

It stays on loading for an extremely long time/ forever

**Comment by xgi** [comment]
Fixed with v1.3.0 of the MangaKik extension. Thanks!
