### ISSUE TITLE
IsekaiScan Source Bug

### ISSUE THREAD

**Issue by dragow0lf** [xgi/houdoku-extensions#26]
### Acknowledgements

- [X] Ensure that your extensions are up-to-date (check the Extensions tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with Houdoku itself, open a ticket in the [Houdoku repo](https://github.com/xgi/houdoku/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.8.0

### Affected extension(s)

IsekaiScan 1.2.0

### Steps to reproduce

Open any manga using the source
Add the manga to your library
Try reading the manga

### Expected behavior

Should have listed all available chapters which you would then click on to read the chapter

### Actual behavior

It shows no chapter

**Comment by xgi** [comment]
I fixed the underlying issue for this that was affecting several madara-based extensions, thanks!

**Comment by dragow0lf** [comment]
IsekaiScan doesn't work at all now😅

**Comment by xgi** [comment]
Hm, it seems like IsekaiScan has an additional captcha that isn't getting passed. I have a fix, but it'll require a small Houdoku update too -- will get that done sometime next week. Thanks for the report!

**Comment by xgi** [comment]
Fixed with Houdoku 2.8.1 and IsekaiScan extension version 1.4.0. Thanks!
