### ISSUE TITLE
Chapters of series added from Mangasee don't Have Titles.

### ISSUE THREAD

**Issue by Zakaria-ouertani** [xgi/houdoku-extensions#27]
### Acknowledgements

- [X] Ensure that your extensions are up-to-date (check the Extensions tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with Houdoku itself, open a ticket in the [Houdoku repo](https://github.com/xgi/houdoku/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.8.1

### Affected extension(s)

Mangasee 1.1.2

### Steps to reproduce

1. Add series from Mangasee.

### Expected behavior

Titles Should Appear.

### Actual behavior

Titles don't Appear.

### Additional information

Windows 10 Version 21H1, Build 19043.156
![Houdoku_uBbd4l26Cf](https://user-images.githubusercontent.com/75418838/160280597-62f6b8e8-8a9d-48c1-a37e-f6deda7f1dd6.png)
![Houdoku_XtQALCee0q](https://user-images.githubusercontent.com/75418838/160280601-ab0422e4-4e9f-49f7-975d-29d60d2a0595.png)
6

**Comment by xgi** [comment]
I don't think MangaSee provides chapter titles; some websites only provide the chapter #. Looking here: https://mangasee123.com/manga/Peerless-Dad you can see the chapter list is only `Episode 212`, `Episode 211`, etc. If the website doesn't include titles then there's no way for Houdoku to know them.
