### ISSUE TITLE
[Source Request] Reaper Scans

### ISSUE THREAD

**Issue by Subtilizer28** [xgi/houdoku-extensions#28]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [x] Write a concise title for this ticket in the field above.

### Source name

Reaper Scans

### Source URL

https://reaperscans.com/all-series/comics/

### Source language(s)

English

**Comment by xgi** [comment]
Moved to #85
