### ISSUE TITLE
[ReadComicOnline] No series were found

### ISSUE THREAD

**Issue by crxssed7** [xgi/houdoku-extensions#29]
### Acknowledgements

- [X] Ensure that your extensions are up-to-date (check the Extensions tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with Houdoku itself, open a ticket in the [Houdoku repo](https://github.com/xgi/houdoku/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.8.1

### Affected extension(s)

ReadComicOnline 1.0.1

### Steps to reproduce

1. Go to "Add series".
2. Switch to ReadComicOnline.
3. See message "No series were found".
4. Search for a comic.
5. See same message again.

### Expected behavior

It should load all the comics found in a search.

### Actual behavior

The exact message is "Sorry, no series were found with the current settings."

### Additional information

So far from what I have tested, ReadComicOnline is the only one affected.

**Comment by xgi** [comment]
It seems this website has a more advanced Cloudflare protection than ones I've seen before, which blocks Houdoku from accessing content on the website. I have a bypass for most Cloudflare blocks, but this one is more strict -- I did some experimenting but I haven't found a functional solution yet.
