### ISSUE TITLE
[Hyakuro] Series not loading because of inexistent domain

### ISSUE THREAD

**Issue by Valdorz** [xgi/houdoku-extensions#34]
### Acknowledgements

- [X] Ensure that your extensions are up-to-date (check the Extensions tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with Houdoku itself, open a ticket in the [Houdoku repo](https://github.com/xgi/houdoku/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.8.2

### Affected extension(s)

Hyakuro 1.0.0

### Steps to reproduce

1. Installing the Hyakuro extension from the *Extensions* tab.
2. Selecting the Hyakuro extension from the dropdown panel in the *Add Series* tab.
3. Getting an error message `Sorry, no series were found with the current settings.`.
4. Testing the actual web and checking if it's been blocked in my region, thus testing a VPN, different DNS's and Tor browser; but failing to load the page in each and every case.
5. Searching if the scanlation group is dead, though it seems they're still active on MangaDex, now without a web page.

### Expected behavior

The extension should have loaded at least some titles when in the *Add Series* tab, or been able to search for some of the available.

### Actual behavior

The extension hasn't loaded any titles, nor has it been able to load any title from the search box, most surely due to the shutdown of the page, though it seems the scanlation group is still active on Mangadex.

**Comment by xgi** [comment]
This group appears to release only on MangaDex now; I've removed this extension. Thanks!
https://mangadex.org/group/85dca5a5-d95b-4992-a198-b4895a767092
