### ISSUE TITLE
[Tortuga Çeviri] Series not loading because of possible shutdown

### ISSUE THREAD

**Issue by Valdorz** [xgi/houdoku-extensions#41]
### Acknowledgements

- [X] Ensure that your extensions are up-to-date (check the Extensions tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with Houdoku itself, open a ticket in the [Houdoku repo](https://github.com/xgi/houdoku/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.8.2

### Affected extension(s)

Tortuga Çeviri 1.0.0

### Steps to reproduce

1. Installing the Tortuga Çeviri extension from the *Extensions* tab.
2. Selecting the Tortuga Çeviri extension from the dropdown panel in the *Add Series* tab.
3. Getting an error message `Sorry, no series were found with the current settings.`.
4. Testing the actual web and checking if it's been blocked in my region, thus testing a VPN, different DNS's and Tor browser; but failing to load the page in each and every case.
5. Searching if the site's down and possibly being the case, though I've not been able to check if the scanlation group has stopped working.

### Expected behavior

The extension should have loaded at least some titles when in the *Add Series* tab, or been able to search for some of the available.

### Actual behavior

The extension hasn't loaded any titles, nor has it been able to load any title from the search box, most surely due to the shutdown of the scanlation group, though I've not been able to confirm this last thing.

**Comment by xgi** [comment]
The domain for this source appears to have changed (`tortugaceviri.com` -> `tortuga-ceviri.com`).

**Comment by Valdorz** [comment]
> The domain for this source appears to have changed (`tortugaceviri.com` -> `tortuga-ceviri.com`).

Though it still doesn't seem to be working in Houdoku, just checked and the extension's still flagged with the old domain in the *Extensions* tab.

**Comment by xgi** [comment]
Sorry, I wasn't claiming that it was resolved, just clarifying that the source still exists. I didn't close the issue.

**Comment by Valdorz** [comment]
Thought so, I should have been the one clarifying my answer, sorry for the inconvenience.

**Comment by xgi** [comment]
Updated this extension.
