### ISSUE TITLE
Spanish LATAM Language Filter

### ISSUE THREAD

**Issue by kouyo-quotient** [xgi/houdoku-extensions#45]
### Acknowledgements

- [X] Ensure that your extensions are up-to-date (check the Extensions tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with Houdoku itself, open a ticket in the [Houdoku repo](https://github.com/xgi/houdoku/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.8.2

### Affected extension(s)

MangaDex 1.3.1

### Steps to reproduce

1. Go to settings and set the language filter to only show chapters in Spanish LATAM
2. Go to any manga that has a Spanish LATAM chapter

### Expected behavior

It should show chapters in Spanish LATAM

### Actual behavior

They doesn't show at all

### Additional information

I've also tested with Spain Spanish and the chapters show correctly, the Spanish LATAM flag also doesn't show, I'm not sure if this issue is only happening with the MangaDex extension since it's the only extension that supports Spanish (as far as I know), and I also wasn't sure if this bug report should be on the main repo, so let me know if I made a mistake

**Comment by xgi** [comment]
This was caused by the MangaDex extension missing a mapping for the Spanish LATAM language code, so it wasn't properly detecting the chapter language.

Updated the MangaDex extension to 1.3.2 to fix this; please update the extension and refresh the manga. Thanks!
