### ISSUE TITLE
[Source Request] MangaHere

### ISSUE THREAD

**Issue by Gun-Striker** [xgi/houdoku-extensions#46]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

MangaHere

### Source URL

https://www.mangahere.cc/

### Source language(s)

English

**Comment by xgi** [comment]
Moved to #85
