### ISSUE TITLE
[Source Request] MangaReader.to

### ISSUE THREAD

**Issue by dragow0lf** [xgi/houdoku-extensions#47]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

MangaReader

### Source URL

mangareader.to

### Source language(s)

English, Japanese

### Additional information

High-quality scans.
Anti-overload with back-up server.
Fast content updates.
Zero ads and pop-ups.

Sorry for this post as there was another one requesting the same extension, but that request was a long time ago and still no extension for it.

**Comment by xgi** [comment]
Thanks for the request, but I don't want duplicates for the same source. I don't only work on the newest requests, I mostly choose arbitrarily. Feel free to vouch in the existing request though.
