### ISSUE TITLE
(SOURCE REQUEST) XOXOCOMICS COMIC CASTLE VIEWCOMICS

### ISSUE THREAD

**Issue by jeybsss** [xgi/houdoku-extensions#49]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

XOXOCOMICS/COMICASTLE/VIEWCOMICS

### Source URL

https://xoxocomics.net/ https://comicastle.org/home https://viewcomics.me/

### Source language(s)

English

**Comment by drcorg** [comment]
+1 to xoxocomics, it's the second biggest comics site after readcomiconline, which hasn't worked in a while.

**Comment by DeadAmericana** [comment]
I would also love to see this. Would be a huge addition.

**Comment by xgi** [comment]
Moved to #85
