### ISSUE TITLE
[SOURCE REQUEST] MangaWorld

### ISSUE THREAD

**Issue by yoshino2923** [xgi/houdoku-extensions#51]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

MangaWorld

### Source URL

https://www.mangaworld.in/

### Source language(s)

Italian

### Additional information

Sorry for the bother, this is the only good Italian manga website, all the others are only translations team's websites which have only a few manga, so i would like if you added it, Thank you. (English isn't my first language, so sorry in advance if there is any mistekes)

**Comment by xgi** [comment]
Moved to #85
