### ISSUE TITLE
Entry in library shows there are (new) chapters when there are none (MangaDex)

### ISSUE THREAD

**Issue by ScruffiX** [xgi/houdoku-extensions#53]
### Acknowledgements

- [X] Ensure that your extensions are up-to-date (check the Extensions tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with Houdoku itself, open a ticket in the [Houdoku repo](https://github.com/xgi/houdoku/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

v2.9.2

### Affected extension(s)

MangaDex

### Steps to reproduce

Add Series from MangaDex to Library

### Expected behavior

Available Chapters shown represent available chapters to read.

### Actual behavior

When adding some series from MangaDex some series are marked as having chapters / new chapters. But when entering the entry there are no said chapters.

Example entry: Hyper Luck 
![image](https://user-images.githubusercontent.com/15036358/183489071-380ed6d9-088d-46cb-982d-10d114d210b5.png)

All chapters available in the Manhwa have been marked as read, yet it still shows there are more chapters to read
![image](https://user-images.githubusercontent.com/15036358/183489309-432572f3-3d45-46ac-b824-3209511dca09.png)

The unread 9 chapters do not exist on MangaDex itself.

Some Other examples:
![image](https://user-images.githubusercontent.com/15036358/183489411-ab0d7729-bc63-49a8-92d3-2c58deb9cdd9.png)
![image](https://user-images.githubusercontent.com/15036358/183489434-55654ce9-3aeb-421c-9aa1-b42897963f04.png)

![image](https://user-images.githubusercontent.com/15036358/183489489-323726b9-6d8f-4084-95ab-9bbfdc15df28.png)
When re-adding this series it says that there are 5 chapters available. Marking the 4 available ones as read brings the following result.
![image](https://user-images.githubusercontent.com/15036358/183489503-7a5aaa28-ae26-492c-9a55-d622b85adfe7.png)

![image](https://user-images.githubusercontent.com/15036358/183489545-c4064aaf-e958-461c-bfbe-c1a50e13f71d.png)
![image](https://user-images.githubusercontent.com/15036358/183489563-ec455656-5bac-42e6-9a5f-2f63a4369fc6.png)

### Additional information

It only seems to affect some chosen shows and doesn't feel random i guess.
I only experienced this issue with MangaDex entries.
This is an annoying issue because you always see unread shows pop up when there are no new chapters (I sort by Unread ascending).

I am guessing that Houdoku gets the chapter status from somewhere else then the Extension itself for this Error to happen?

**Comment by xgi** [comment]
The issue was the displayed number included chapters from languages that aren't displayed (there's a setting for this, `Settings->General->Chapter Languages`). For Hyper Luck for example, there are Portuguese chapters going to 29, so even when English chapters up to 20 were read, it still thinks there are 9 remaining.

With https://github.com/xgi/houdoku/commit/5d74231d651caa5cba1b1fadb87cb4b1207dc47c the count will now only include chapters that match the language setting. Thanks!
