### ISSUE TITLE
[Source Request] TCB Scans

### ISSUE THREAD

**Issue by MoLP5776** [xgi/houdoku-extensions#54]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

TCB Scans

### Source URL

http://tcbscans.com or https://onepiecechapters.com/

### Source language(s)

English

**Comment by double1600** [comment]
Add this one because it has rly good One Piece scans and translations

**Comment by xgi** [comment]
Moved to #85
