### ISSUE TITLE
[Source Request] BILIBILI COMICS

### ISSUE THREAD

**Issue by ghost** [xgi/houdoku-extensions#55]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

BilibiliComics

### Source URL

https://www.bilibilicomics.com

### Source language(s)

English

### Additional information

Bilibili Comics is an official site to read licenced manhua. All the Manhua in this site are of original quality (same quality from the author).

Three types of image resolution is offered. i.e, Raw, hd, sd.
- Raw Image has more (width x height) than hd quality image.
- hd Image has more (width x height) than sd quality image.
- The image quality for every image is webp.

There are two ways to read manhua in this site. 
1. To pay for each chapter after the free chapters.
2. To wait for a certain amount of time to unlock the chapters permanently.

Example Manhua Link: https://www.bilibilicomics.com/detail/mc204
Free Chapter Link: https://www.bilibilicomics.com/mc204/16762
Paid Chapter Link: https://www.bilibilicomics.com/mc204/24605

To access paid chapters, a site login feature is needed.

I uploaded .jpg images as .webp is not supported by github. The original .webp images can be found in the .zip file below.
[Example Images.zip](https://github.com/xgi/houdoku-extensions/files/9388877/Example.Images.zip)

The below image is not upscaled.
![Not Upscaled](https://user-images.githubusercontent.com/111482404/185786973-d8be2918-f389-4984-aae9-c3c53b076d37.jpg)
The below Image was downloaded using tachiyomi.
![From Tachiyomi](https://user-images.githubusercontent.com/111482404/185786965-fcb14ab4-93fa-4f5e-86f1-30f023d659d0.jpg)

The first image has a resolution of 2400 x 6168. The second image is downloaded using tachiyomi and has a resolution of 1200 x 3084. The quality of the first image is better (not upscaled). Just for reference.

**Comment by xgi** [comment]
Moved to #85
