### ISSUE TITLE
Pls Add Arabic Mangas Extensions Like "Gmanga/gatemanga/. . ."

### ISSUE THREAD

**Issue by ImSIFO** [xgi/houdoku-extensions#56]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

Gmanga

### Source URL

https://gmanga.me

### Source language(s)

Arabic

**Comment by xgi** [comment]
Moved to #85
