### ISSUE TITLE
Manga Reader

### ISSUE THREAD

**Issue by AdnanShaqur** [xgi/houdoku-extensions#58]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

Manga Reader

### Source URL

https://mangareader.to/

### Source language(s)

English

### Additional information

Please Add It

**Comment by xgi** [comment]
Moved to #85
