### ISSUE TITLE
Komga: "Objects are not valid as a React child" while trying to add series

### ISSUE THREAD

**Issue by noaione** [xgi/houdoku-extensions#59]
### Acknowledgements

- [X] Ensure that your extensions are up-to-date (check the Extensions tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with Houdoku itself, open a ticket in the [Houdoku repo](https://github.com/xgi/houdoku/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.10.1

### Affected extension(s)

Komga 1.1.3

### Steps to reproduce

1. Add Komga extension
2. Try to add a new series

### Expected behavior

It shows the modal and I can add the series to my library

### Actual behavior

It shows the Error modal/boundary with the following error:
```js
Objects are not valid as a React child (found: object with keys {name, role}). If you meant to render a collection of children, use an array instead.
```

**Logs:**
[main.log](https://github.com/xgi/houdoku-extensions/files/9621950/main.log)
[renderer.log](https://github.com/xgi/houdoku-extensions/files/9621951/renderer.log)

### Additional information

Komga Server version: 0.157.2
OS: Windows 11 Home 22622.598

**Comment by xgi** [comment]
Seems this was because of improperly parsing the authors list. Updated to 1.1.4, thanks! 71e39d365793202d845d0f17031173da2ae4291f
