### ISSUE TITLE
Could you add extension support for this webpage?

### ISSUE THREAD

**Issue by camiflappy** [xgi/houdoku-extensions#6]
Hello, I was wondering if you could please add support for this site, as it's the one with the most readily available spanish translations and access to both online and downloadable resources.

[Site](https://lectormanga.com/)

Please do consider it, and thank you in advance for your response.
Also, I wanted to thank you, as I have found it very comfortable to use your software.

**Comment by xgi** [comment]
I've added LectorManga with #7. It will be available after the next Houdoku update (~1 week).

Make sure you add Spanish chapters in Houdoku by going to Settings->General->Chapter Languages and adding "Spanish (ES)".

Thanks for the request!
