### ISSUE TITLE
MangaLife isn't loading any series

### ISSUE THREAD

**Issue by CookieSamuraiSan** [xgi/houdoku-extensions#60]
### Acknowledgements

- [x] Ensure that your extensions are up-to-date (check the Extensions tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with Houdoku itself, open a ticket in the [Houdoku repo](https://github.com/xgi/houdoku/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.10.1

### Affected extension(s)

MangaLife 1.3.2

### Steps to reproduce

1. Add series.
2. Choose MangaLife extension.
3. Click on whatever manga you want.

### Expected behavior

It should have given me the series details and let me add the series to my library.

### Actual behavior

![TloQpGx](https://user-images.githubusercontent.com/114139583/191689843-42c00e0e-7de2-426a-8ca7-38439ac40825.png)

Keep loading the series endlessly and nothing happens.

### Additional information

Everything is fine on the site, seems like the bug is from Houdoku.

**Comment by xgi** [comment]
Should be fixed with 1.3.3, thanks!
