### ISSUE TITLE
Request for the Mangareader.to extension

### ISSUE THREAD

**Issue by LustfulRose** [xgi/houdoku-extensions#62]
### Acknowledgements

- [X] Ensure that your extensions are up-to-date (check the Extensions tab).
- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] If this is an request for Houdoku itself, open a ticket in the [Houdoku repo](https://github.com/xgi/houdoku/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Affected extension(s)

https://mangareader.to/

### Feature request

Honestly I won't ask for any features. It is good enough.

**Comment by xgi** [comment]
Moved to #85
