### ISSUE TITLE
Blogtruyen

### ISSUE THREAD

**Issue by CuongBa956** [xgi/houdoku-extensions#63]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

Blogtruyen

### Source URL

https://blogtruyen.vn/

### Source language(s)

Vietnamese

**Comment by xgi** [comment]
Moved to #85
