### ISSUE TITLE
Hentaivn

### ISSUE THREAD

**Issue by CuongBa956** [xgi/houdoku-extensions#64]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

Hentaivn

### Source URL

https://hentaivn.la/

### Source language(s)

Vietnamese

**Comment by xgi** [comment]
Moved to #85
