### ISSUE TITLE
[Source Request] remanga.org

### ISSUE THREAD

**Issue by monolit** [xgi/houdoku-extensions#66]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

Remanga

### Source URL

https://remanga.org/

### Source language(s)

Russian

**Comment by xgi** [comment]
I'm getting access denied by Cloudflare (likely from region restrictions), so I'm not able to implement this.

**Comment by xgi** [comment]
Moved to #85
