### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by monolit** [xgi/houdoku-extensions#67]
### Acknowledgements

- [X] Ensure that your extensions are up-to-date (check the Extensions tab).
- [X] Check that there is not an existing ticket for this request, and that it is not related to an existing ticket.
- [X] If this is an request for Houdoku itself, open a ticket in the [Houdoku repo](https://github.com/xgi/houdoku/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Affected extension(s)

Mangadex. Maybe some others

### Feature request

sort manga by translation language
![imageee](https://user-images.githubusercontent.com/53448546/194777745-3198c466-1350-4ade-93c2-68f341beadbd.png)

**Comment by xgi** [comment]
There's a `Chapter languages` option in the settings to choose which languages to show. I don't plan on adding this to individual series pages.
