### ISSUE TITLE
Cubari

### ISSUE THREAD

**Issue by rollingmoai** [xgi/houdoku-extensions#72]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

Cubari

### Source URL

https://cubari.moe/

### Source language(s)

Multi

### Additional information

[Cubari](https://cubari.moe/) is a proxy for other manga websites that also supports Imgur and Github Gists.

See [Tachiyomi Extension](https://github.com/tachiyomiorg/tachiyomi-extensions/tree/master/src/all/cubari):
![image](https://user-images.githubusercontent.com/75471378/197446131-ab2bf777-a8cd-48ad-9b6e-d7d26664277f.png)

**Comment by xgi** [comment]
Moved to #85
