### ISSUE TITLE
[Source Request] Kiryuu

### ISSUE THREAD

**Issue by knapah** [xgi/houdoku-extensions#75]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

Kiryuu

### Source URL

https://kiryuu.id/

### Source language(s)

Indonesia

**Comment by xgi** [comment]
Moved to #85
