### ISSUE TITLE
No manga is displayed when choosing this extension

### ISSUE THREAD

**Issue by SinisterGosu** [xgi/houdoku-extensions#78]
### Acknowledgements

- [X] Ensure that your extensions are up-to-date (check the Extensions tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with Houdoku itself, open a ticket in the [Houdoku repo](https://github.com/xgi/houdoku/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

v2.11.0

### Affected extension(s)

Toonily 1.7.1

### Steps to reproduce

1. Click Add Series
2. Select Toonily from drop down menu
3. Wait for it to load manga

### Expected behavior

Display manga from Toonily.

### Actual behavior

After loading, no manga appears.

**Comment by xgi** [comment]
Fixed with 7297253b81407d236a194f2a9af15ad81d3fc81d
