### ISSUE TITLE
[Source Request] for Manhwa18

### ISSUE THREAD

**Issue by toprak** [xgi/houdoku-extensions#81]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

Manhwa18

### Source URL

https://manhwa18.cc/

### Source language(s)

English

**Comment by xgi** [comment]
Moved to #85
