### ISSUE TITLE
Tachidesk

### ISSUE THREAD

**Issue by toprak** [xgi/houdoku-extensions#82]
### Acknowledgements

- [X] Verify that this extension has not already been added (check the Extensions tab).
- [X] Check whether there is another ticket requesting this source.
- [X] Write a concise title for this ticket in the field above.

### Source name

Tachidesk

### Source URL

https://github.com/Suwayomi/Tachidesk-server

### Source language(s)

Every language

### Additional information

I wrote in the Discussion section, I don't know if you ignored it or not, using Tachidesk's extension library will definitely help us and we will save a lot of time, right now mangadex is broken, we can't see the actual manhwas because toonily family mode came, I think it would be much more comfortable to make a tachidesk extension rather than constantly dealing with them, it also has apis in the form of swagger-ui

**Comment by xgi** [comment]
Moved to #85
