### ISSUE TITLE
🎀 Request an Extension

### ISSUE THREAD

**Issue by xgi** [xgi/houdoku-extensions#85]
This issue is to track NEW EXTENSION REQUESTS. If there's an extension you want added that isn't in Houdoku, leave a comment here and I'll add it to the list. I prioritize updates at my own discretion, but PRs are welcome if you want to develop one yourself.

For bug reports or feature requests for EXISTING EXTENSIONS, [create a new issue](https://github.com/xgi/houdoku-extensions/issues/new/choose).

| Name  | URL | Status | Note
| - | - | - | - |
| AnzManga        | https://www.anzmangashd.com/    | 📝 TODO    |
| AsuraScans      | https://www.asurascans.com/     | 📝 TODO    |
| BILIBILI COMICS | https://www.bilibilicomics.com/ | 📝 TODO    |
| Blogtruyen      | https://blogtruyen.vn/          | 📝 TODO    |
| Comicastle      | https://comicastle.org          | 📝 TODO    |
| Cubari          | https://cubari.moe              | 📝 TODO    |
| Desu.me         | https://desu.me                 | 📝 TODO    |
| e-hentai        | https://e-hentai.org            | 📝 TODO    |
| GMANGA          | https://gmanga.me               | 📝 TODO    |
| GoldenMangas    | https://goldenmanga.top         | 📝 TODO    |
| HentaiFox       | https://hentaifox.com           | 📝 TODO    |
| Hentaivn        | https://hentaivn.la/            | 📝 TODO    |
| Kiryuu          | https://kiryuu.id/              | 📝 TODO    |
| MangaHere       | https://www.mangahere.cc/       | 📝 TODO    |
| MangaReader.to  | https://mangareader.to          | 🚫 BLOCKED | Page images are scrambled and need to be decoded client-side -- requires client change. |
| MangaWorld      | https://www.mangaworld.in/      | 📝 TODO    |
| Manhwa18        | https://manhwa18.cc             | 📝 TODO    |
| MyReadingManga  | https://myreadingmanga.info     | 📝 TODO    |
| NitroScans      | https://nitroscans.com          | 📝 TODO    |
| ReadM           | https://readm.org/              | 📝 TODO    |
| ReaperScans     | https://reaperscans.com         | 📝 TODO    |
| remanga         | https://remanga.org/            | 🚫 BLOCKED    | Blocked in my region
| Submanga        | https://submanga.io/            | 📝 TODO    |
| Tachidesk       | N/A                             | 📝 TODO    |
| TCB Scans       | https://onepiecechapters.com    | 📝 TODO    |
| ViewComics      | https://viewcomics.me/          | 📝 TODO    |
| WebtoonXYZ      | https://www.webtoon.xyz         | 📝 TODO    |
| Westmanga       | https://westmanga.info/         | 📝 TODO    |
| XOXOComics      | https://xoxocomics.net/         | 📝 TODO    |

**Comment by mswish** [comment]
**Acknowledgements**

- [x]     Verify that this extension has not already been added (check the Extensions tab).
- [x]     Check whether there is another ticket requesting this source.
- [x]     Write a concise title for this ticket in the field above.

**Source** name

Bato.to

**Source URL**

[https://bato.to/](url)

**Source language(s)**

Multi-lingual

**Additional information**

[https://bato.to/v3x](url)

**Comment by ObedPM** [comment]
Source name: 
TuMangaOnline 

Source URL:
https://lectortmo.com/

Source language:

Spanish (Español)

**Comment by MedInstead** [comment]
Source name

opscans

Source URL

https://opscans.com

Source language(s)

Multi-lingual

**Comment by Ashxzyl** [comment]
Can you update--> https://readcomiconline.li/ 
or
 add https://comiconlinefree.org/ extensions, please? 
 The readcomiconline extension in the program currently looks like it hasn't been updated cuz most of the comics are absent there. Thanks.

**Comment by LadyHaywood** [comment]
Source name
Mangago.me

Source URL
https://www.mangago.me/

Source language(s)
Multi-lingual

**Comment by dsa64adsikjgh** [comment]
Source name
Webtoons (Line)

Source URL
https://www.webtoons.com/en/

Source language(s)
Multi-lingual

**Comment by ghost** [comment]
Source name
Tsuki Mangás

Source URL
https://tsuki-mangas.com/

Source Language
Português(BR)

**Comment by dunkmask2407** [comment]
### **1. Source name**
> Sushi-Scan
> 
>  Source URL
> https://sushiscan.net/
> 
> Source language
> French(FR)

### **2. Source name**
> Manga Plus by Shueisha
> 
> Source URL
> https://mangaplus.shueisha.co.jp/
> 
> Source language(s)
> Multi-lingual

### **3. Source name**
> Manhwa18
> 
> Source URL
> https://manhwa18.cc/
> 
> Source language(s)
> Multi-lingual

### **4. Source name**
> Rawkuma
> 
> Source URL
> https://rawkuma.com/
> 
> Source language(s)
> Multi-lingual

### **5. Source name**
> JapScan
> 
> Source URL
> https://www.japscan.lol/
> 
> Source language
> French(FR)

### **6. Source name**
> Manganato
> 
> Source URL
> https://www.manganato.com/
> 
> Source language
> English(EN)

**Comment by xgi** [comment]
Extensions have moved to https://github.com/xgi/tiyo
- New ticket to track extension requests: https://github.com/xgi/tiyo/issues/1
- More information: https://github.com/xgi/houdoku/discussions/322
