### ISSUE TITLE
ComicK extension no longer works

### ISSUE THREAD

**Issue by dodumosu** [xgi/houdoku-extensions#88]
### Acknowledgements

- [X] Ensure that your extensions are up-to-date (check the Extensions tab).
- [X] Check that there is not an existing ticket for this issue, and that it is not related to an existing ticket.
- [X] If this is an issue with Houdoku itself, open a ticket in the [Houdoku repo](https://github.com/xgi/houdoku/issues/new/choose) instead.
- [X] Write a concise title for this ticket in the field above.

### Houdoku version

2.12.0

### Affected extension(s)

ComicK 1.2.1

### Steps to reproduce

- Add the ComicK extension
- Try to add a series using the extension. Nothing will be loaded
- If you already have an existing series loaded from the extension, refreshing or trying to download any chapters will fail

### Expected behavior

Adding a series/refreshing/downloading using the extension should work

### Actual behavior

Nothing using the extension works anymore. Opening the console reveals errors

**Comment by carks32** [comment]
I don't know if it's fine to revive this but ComicK doesnt work as of now because they moved domains from .fun to .app awhile back.

**Comment by xgi** [comment]
> I don't know if it's fine to revive this but ComicK doesnt work as of now because they moved domains from .fun to .app awhile back.

Fixed with 6dadfd4b9d627690539b118223bea711d6bb6f74. In the future, feel free to open a new issue if something's still broken!
